/// Word list used by the passphrase generator.
///
/// Words are short, unambiguous and lowercase. The list is de-duplicated at
/// load time so entropy reported to the user (log2(length) per word) is always
/// computed from the real number of distinct choices.
class PassphraseWords {
  const PassphraseWords._();

  static final List<String> words = _raw
      .split(' ')
      .where((w) => w.isNotEmpty)
      .toSet()
      .toList(growable: false);

  static const String _raw =
      'able acid acorn actor adapt agent alarm album alert alley alpha amber '
      'amount anchor angle ankle apple april arbor arch arctic arena argue '
      'armor arrow ash aside asset atlas atom attic audio august aunt autumn '
      'avenue awake award axis bacon badge bagel baker balance balcony bamboo '
      'banana banjo barley barn basil basket batch beach beacon beam bean '
      'bear beaver bench berry beta bicycle binder birch bird bishop bison '
      'black blade blanket blend blink block bloom blue board boat bolt bonus '
      'book boot border bottle boulder bowl brace branch brass brave bread '
      'breeze brick bridge bright bronze brook broom brown brush bubble '
      'bucket buffalo bugle build bulb bundle bunker burst butter button '
      'cabin cable cactus cake calm camera camp canal candle canoe canvas '
      'canyon cape captain carbon cargo carpet carrot carve castle catalog '
      'cattle cedar cell cement census center chain chalk chamber channel '
      'chapter charm chart cheese cherry chess chest chief chime chorus '
      'cider cinema circle citrus city civic clamp clarity clay clever cliff '
      'climb clock cloud clover club coach coast cobalt cocoa coffee coil '
      'collar colony column comet compass copper coral corner cosmic cotton '
      'county couple courage cover coyote crane crater crayon cream credit '
      'crest cricket crimson crisp crown crystal cube cumin curl current '
      'curtain cushion cycle cypress daisy dance dandy dawn daylight deacon '
      'debate decade deck decoy deer delta denim depot desert design desk '
      'detail device diagram diamond diary diesel digit dinner direct disk '
      'dive dock doctor dolphin domain donut double dove draft dragon drama '
      'drawer dream drift drill drum dryer dune dusk eagle early earth east '
      'echo eclipse edge editor effort eight elbow elder electric elegant '
      'element elite ember emerald empire enamel energy engine enter envelope '
      'equal equator era escape essay estate ether ethics europe evening '
      'event exact exhale exit expert extra fabric facet factor falcon family '
      'fancy fantasy farm feather fence fern ferry fiber fiction field figure '
      'filter finance finch finger fire first fish flag flame flash fleet '
      'flint float floor flour flower fluid flute focus fog folder forest '
      'forge fortune forum fossil fountain fox frame freedom fresh friend '
      'frost fruit fuel funnel future gadget galaxy gallery garden garlic '
      'gate gather gauge gazelle gear gecko gentle geology ghost giant '
      'ginger giraffe glacier glass glide globe glove glow golden gondola '
      'goose gorge grain grand granite grape graph grass gravel green grid '
      'grill grove guard guitar gulf gypsum habit hammer hangar harbor '
      'harvest hatch haven hawk hazel heart heat hedge helium helmet herald '
      'herb hero hexagon hiking hill hinge history hobby hollow honey hood '
      'horizon horse hotel hour house hover human humble hunter hurdle hydro '
      'ice icon igloo image impact inch index indigo ingot ink inlet insect '
      'inside iron island ivory jacket jade jaguar jasmine jelly jersey jewel '
      'jigsaw jockey jolly journal joy judge juice jungle juniper jury kayak '
      'kernel kettle keyboard kidney kind king kiosk kite kitten knight knot '
      'koala lace ladder lagoon lake lamp lantern lapis large laser latch '
      'laurel lava lawn layer leaf ledge legacy legend lemon lens leopard '
      'level lever liberty library light lilac lily lime linen lion liquid '
      'listen little lively lizard llama lobby local locker lodge logic lotus '
      'lounge lucky lumber lunar lunch lyric machine magic magnet mahogany '
      'maize major mammal mango manual maple marble margin marina market '
      'marsh mason master matrix meadow medal melody memory mentor mercury '
      'mesa metal meteor method metric micro midnight mighty milk mill mimic '
      'mineral mint mirror mission mist mobile modern module moment monarch '
      'monitor monsoon moon moral mosaic moss motion motor mountain mouse '
      'muffin mural museum music mustard myrtle nation native nature navy '
      'nebula nectar needle neon nest network neutral newt nickel night '
      'nimble noble nomad noodle north notch novel nozzle nurse nutmeg oak '
      'oasis object ocean octave october offer office olive omega onion onyx '
      'opal opera optic orange orbit orchard orchid order organ origin osprey '
      'otter outdoor oval oven owl oxide oxygen oyster pacific packet paddle '
      'pageant paint palace palm panda panel panther paper papaya parade '
      'parcel parent parish parka parrot pasta pastel patch path patient '
      'patrol pattern peach peak pearl pebble pecan pedal pelican pencil '
      'penguin pepper perch period petal phase phoenix photo piano picnic '
      'pigment pilot pine pioneer pipe pistol pivot pixel pizza planet plank '
      'plasma plate plaza pledge plum plush pocket poem polar pollen pond '
      'pony poplar poppy porch portal poster potato pottery powder power '
      'prairie praise prawn precise prefix prelude premier press prime prism '
      'prize probe profile project promise proton public pudding puffin '
      'pulley pulse pumpkin punch puzzle pylon pyramid quality quantum '
      'quarry quartz quest quiet quill quilt quota rabbit racket radar radio '
      'radish rafter rail rain rally ranch random range rapid rare raven '
      'razor reader realm reason rebel recipe record reef refuge region relay '
      'relic remedy render rescue reserve resin retina return rhino rhythm '
      'ribbon rice ridge rifle rigid ring ripple river road robin robot '
      'rocket rodeo roof rookie room root rope rose roster rotor round route '
      'royal rubber ruby rudder rugby ruler runner rural rustic sable saddle '
      'safari saffron sage sail salad salmon salt sample sand sapphire satin '
      'sauce savanna scale scarf scenic school science scout screen scroll '
      'sculpt season second sector sedan seed segment select senate sensor '
      'sentry sequoia serene series sermon settle shadow shale shape shard '
      'shark sharp shelf shell shield shine ship shore short shovel shrimp '
      'shuttle sierra signal silent silk silver simple siren sketch skill '
      'skyline slate sleek slide slope small smart smoke snap snow soap '
      'social socket soda solar solid sonic soprano sorbet sound source south '
      'space spade spark sphere spice spider spike spiral spirit splash '
      'spoon spring sprout spruce square squash stable stadium staff stage '
      'stamp stand star statue steady steam steel stellar stereo stitch '
      'stone stork storm stove strand stream street string strong studio '
      'style sugar summit sunset supper surf survey swan sweet swift symbol '
      'syrup system table tablet tackle tactic tailor talent tandem tangle '
      'tape target tavern teacup teal teapot temple tender tennis tent '
      'terrace texture theater theory thermal thicket thorn thread thunder '
      'ticket tide tiger timber tissue title toast token tomato topaz topic '
      'torch total totem toucan tower town track trade trail train tram '
      'transit travel treaty trellis trend triangle tribe trophy tropic '
      'trout truck trumpet trust tulip tumble tundra tunnel turbine turtle '
      'tuxedo twig twilight twine ultra umbrella unicorn union unique unity '
      'update upland urban urchin useful valley valve vanilla vapor vault '
      'vector velvet vendor venture venue verse vessel vibrant victory video '
      'viking villa vine vintage violet violin vision vista vital vivid '
      'vocal voyage waffle wagon walnut walrus warden wardrobe warm water '
      'wave weather weave wedge welcome western whale wheat wheel whisper '
      'white widget willow window winter wire wisdom wolf wonder wood wool '
      'world woven wrench writer yacht yarn year yellow yield yoga young '
      'zebra zenith zephyr zigzag zinc zipper zodiac zone';
}
